* Changelog
** [2023-08-02 Wed 17:44] 0.5.4 Updated Relations
The relations enum has been removed, as it made little sense for a graph.
Added a note field to the ~Relation~ object

[[file:~/Documents/Projects/starintel/spec/doc-nim/changelog.org::*\[2023-01-06 Fri 04:25\] 0.4.0][[2023-01-06 Fri 04:25] 0.4.0]]
** [2023-07-23 Sun 03:42] 0.5.2 Removal of Booker prefix

This was never needed and should never have been a thing, to migrate your code use sed against it just removing the Booker Prefix

#+begin_src shell
find . -type f -exec sed -i 's/Booker//g' {} +
#+end_src


[[file:~/Documents/Projects/starintel/spec/doc-nim/starintel_doc.nimble]]
** [2023-04-05 Wed 18:59] 0.5.0

This is the beginning of the migration from the nested documents.
Not marked as 1.0.0 since there are more changes to be made

Removed all doc parsing, moving to star-formatter (starf)


[[file:~/Documents/Projects/starintel/doc/src/starintel_doc/entities.nim]]
** [2023-01-22 Sun 06:48] 0.4.1
Timestamps from now on are unix timestamps
Requires int64 to use.




* Unreleased
** [2023-01-23 Mon 21:17] 0.4.3
EID and UUID based ids are deprecated
Use md5 or sha1 templates
Added dtypes for more objects and creating of document ids

[[file:~/Documents/Projects/starintel/doc/starintel_doc.nimble::version = "0.4.3"]]
** [2023-01-06 Fri 04:25] 0.4.0
Added ~BookerSocialMPost~ to represent a Social Media post on services such as reddit.
Removed ~owner~ field from ~BookerMessage~ object
Added ~BookerWebDocument~ Not sure if its needed...
** [2023-01-01 Sun 02:01] 0.3.0
Added ~remap~.

~remap~ lets you build a new json document with the selcted fields and same document structure as the input json

Using ~remapInject~ it is possible to inject values into the JsonNode

/*IMPORTANT*/: ~remap~  ~remapInject~ and the parse hooks are *slow*. Around 40K/s time kind of slow, this does not take into account Parsing it into a ~BookerDocument~.
So this is a *convenience* feature for scripting rather then a proper parsing method. May simplify bot creation if 40k docs a second is ok with you.
Bench marks for 10,000,000 json lines

bench code:
#+begin_src nim
benchmark "Test std json":
  for x in countup(1, 10_000_000):
    discard t.parseJson().smartParse(config)
benchmark "Test Jsony":
  for x in countup(1, 10_000_000):
    discard t.fromJson(config)
#+end_src

#+begin_example
CPU Time [Test std json] 286.772s
CPU Time [Test Jsony] 222.768s
#+end_example
Its far from the 200k docs/s then the ~parsePerson~ function clock in at.

[[file:~/Documents/Projects/starintel/doc/starintel_doc.nimble::requires "nim >= 1.6.0"]]
** [2022-12-26 Mon 18:30] 0.2.7
Added new types
Removed optional types from bookerweb objects
*** BookerRelation
Map Relations between objects, will be useful for relating two objects
For example an organization holding a meeting or a protest with BookerPerson object attending it.

*** BookerEvent
Experimental object to represent an event such as a protest.
Will be worked on an expanded with time.

** [2022-12-01 Thu 20:47] 0.2.6
Added targets
Readded EID until local hashing is implemented
